#!/usr/bin/env bash
# This script installs and configures HAproxy

sudo apt update
sudo apt install haproxy -y
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 1217-web-01 34.73.242.80:80 check\n\tserver 1217-web-02 54.209.158.161:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
