#!/usr/bin/env bash
# Kills the process of the before task, searching the id by the full pattern used in the console, in this case the name file
PID=$(pgrep -f '4-to_infinity_and_beyond')
kill "$PID"
