#!/usr/bin/env bash
# This script is displaying "Holberton School" with conditionals to show other sentences.
c=1
while ((c <= 10)); do
    if((c == 4));then
	echo "bad luck"
    elif((c == 8));then
	echo "good luck"
    else
	echo "Holberton School";
    fi
    ((c++))
done	
