#!/usr/bin/env bash
# This script is displaying "Holberton School" with conditionals to show other sentences.
c=1
while ((c <= 20)); do
    echo "$c"
    case $c in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((c++))
done	
