#!/usr/bin/env bash
# This script is displaying if a file exist or not
file=holbertonschool
if [ -e $file ];
then
    echo "holbertonschool file exists"
    if [ -s $file ];
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    echo "holbertonschool is a regular file"
else
    echo "holbertonschool file does not exist";
fi

